### ISSUE TITLE
could not serialize access due to concurrent update

### ISSUE THREAD

**Issue by iamveritas** [bucardo/bucardo#157]
hi
We have exactly the same issue described by [@HaiquanHe](https://github.com/bucardo/bucardo/issues/144), only that we have Bucardo 5.4.1 and postgresql 9.6

"When Bucardo stop sync for some reason(like connection stall) for a long time, after re-active sync , it will error:
2017-01-05 22:34:22 EST xxx xxx ERROR: could not serialize access due to concurrent update
2017-01-05 22:34:22 EST xxx xxx STATEMENT: /* Bucardo 5.3.1 */DELETE FROM public.xxxxxx WHERE device_id = ANY('{{"xxxxxxx"

when delta have a lot of data, it will take a long time to sync , like 7mins, then because there are a lot of data in delta table, and the application may update one of these data at the sycn time, so it fail and error.
any chance anyone can give me some advice how to fix it?
the deltas are growing each minute and the sync between the two DBs is blocked

UPDATE: I've subscribed to https://mail.endcrypt.com/mailman/listinfo/bucardo-general
but then after sending an email to bucardo-general@bucardo.org resulted in

"550 5.1.1 bucardo-general@bucardo.org: Recipient address rejected: undeliverable address: Recipient address lookup failed | 550 5.1.1 bucardo-general@bucardo.org: Recipient address rejected: undeliverable address: Recipient address lookup failed"

thank you very much
Ovi

**Comment by machack666** [comment]
Hi @oviwankenobi thanks for the report on the mailing list breakage; we think we've fixed that now.

**Comment by machack666** [comment]
@oviwankenobi one thing you could try is to disable the `quick_check_delta` for the sync.  i.e.,:

```
$ bucardo update sync foo quick_check_delta=0
```

You might also be able to adjust the `transaction_isolation_level` as well.

**Comment by oviwankenobi** [comment]
I've tried the quick_check_delta=0 not the adjusting the transaction_isolation_level
no success
I ended up purging all deltas, deleting all bucardo settings (sync, db groups and relations, triggers, etc) and re-initializing the objects up to the sync object; now it good again. 
hopefully next time when it goes bonkers we'll notice it early enough to not have so many deltas, in which situation it seems bucardo is failing.

thanks

**Comment by fertiland** [comment]
@machack666 
According to the code,  it seems we still can not change to "Read Commited" isolation level. 
is this fixed by  git commit 624361721aa786afdf7477d6a118ca10dabdbc86? 

=========================================
$self->{pg_isolation_level} = defined $sync->{isolation_level} ? $sync->{isolation_level} :
            $config{isolation_level} || 'serializable';

ALTER TABLE bucardo.bucardo_config ADD CONSTRAINT valid_config_isolation_level
  CHECK (name <> 'isolation_level' OR (setting IN ('serializable','repeatable read')));

ALTER TABLE bucardo.sync    ADD CONSTRAINT sync_isolation_level
  CHECK (isolation_level IS NULL OR (lower(isolation_level) IN ('serializable', 'repeatable read')));

Br.
Hsing

**Comment by machack666** [comment]
It would appear so. Are you using 5.5.0? Because that should incorporate that commit already.

**Comment by laorunsen** [comment]
@machack666
I noticed the follow item in released 5.4.0
- Remove default value from sync.isolation_level, so we can default to 
    the global one when needed.

I wonder 'the global one' means the isolation_level setting in table bucardo.bucardo_config or the 
replication target pg's isolation_level.

when I test with the bucardo version 5.5.0,  the issue still exists. Follow are the logs:

Log 1:  I cannot set the isolation_level the 'read commited.'

bucardo=# select * from bucardo_config where name='isolation_level';
      name       |     setting     |     defval      |                              about                              | type | item |            cdate             
-----------------+-----------------+-----------------+-----------------------------------------------------------------+------+------+------------------------------
isolation_level | repeatable read | repeatable read | Default isolation level: can be serializable or repeatable read |      |      | 2019-01-24 04:47:03.57182+00
(1 row)

bucardo=# select * from sync;
bucardo=# select name, isolation_level from sync;
name  | isolation_level 
-------+-----------------
sync1 | 
(1 row)

bucardo=# update sync set isolation_level='read commited';
ERROR:  new row for relation "sync" violates check constraint "sync_isolation_level"
DETAIL:  Failing row contains (sync1, sync1, sync1, t, t, bucardo_latest, , delete, t, null, active, 0, 0, t, f, t, 00:00:00, 00:00:00, f, 0, null, 500000, read commited, 2019-01-24 06:12:14.721275+00).
bucardo=# update bucardo_config set setting='read commited' where name='isolation_level';
ERROR:  new row for relation "bucardo_config" violates check constraint "valid_config_isolation_level"
DETAIL:  Failing row contains (isolation_level, read commited, repeatable read, Default isolation level: can be serializable or repeatable read, null, null, 2019-01-24 04:47:03.57182+00).




Log2:  Could not serialize still happened
(14362) [Thu Jan 24 06:23:58 2019] MCP Bucardo config:
autosync_ddl              => 'newcol'
bucardo_initial_version   => '5.5.0'
bucardo_vac               => '1'
bucardo_version           => '5.5.0'
ctl_checkonkids_time      => '10'
ctl_createkid_time        => '0.5'
ctl_sleep                 => '0.2'
default_conflict_strategy => 'bucardo_latest'
default_email_from        => 'nobody@example.com'
default_email_host        => 'localhost'
default_email_port        => '25'
default_email_to          => 'nobody@example.com'
email_auth_pass           => ''
email_auth_user           => ''
email_debug_file          => ''
endsync_sleep             => '1.0'
flatfile_dir              => '.'
host_safety_check         => ''
isolation_level           => 'repeatable read'
kid_deadlock_sleep        => '0.5'
kid_nodeltarows_sleep     => '0.5'
kid_pingtime              => '60'
kid_restart_sleep         => '1'
kid_serial_sleep          => '0.5'
kid_sleep                 => '0.5'
log_conflict_file         => 'bucardo_conflict.log'
log_level                 => 'normal'
log_level_number          => '2'
log_microsecond           => '0'
log_showlevel             => '0'
log_showline              => '0'
log_showpid               => '1'
log_showsyncname          => '1'
log_showtime              => '3'
log_timer_format          => ''
mcp_dbproblem_sleep       => '15'
mcp_loop_sleep            => '0.2'
mcp_pingtime              => '60'
mcp_vactime               => '60'
piddir                    => '/var/run/bucardo'
quick_delta_check         => '0'
reason_file               => 'bucardo.restart.reason.txt'
reload_config_timeout     => '30'
semaphore_table           => 'bucardo_status'
statement_chunk_size      => '6000'
stats_script_url          => 'http://www.bucardo.org/'
stopfile                  => 'fullstopbucardo'
syslog_facility           => 'log_local1'
tcp_keepalives_count      => '5'
tcp_keepalives_idle       => '10'
tcp_keepalives_interval   => '3'
vac_run                   => '30'
vac_sleep                 => '120'
warning_file              => ''
(14362) [Thu Jan 24 06:23:59 2019] MCP Activating sync "sync1"
(14362) [Thu Jan 24 06:23:59 2019] MCP Running validate_sync on "sync1"
(14362) [Thu Jan 24 06:23:59 2019] MCP Connecting to database "ses_siteA1" (source)
(14362) [Thu Jan 24 06:23:59 2019] MCP Database "ses_siteA1" Local epoch: 1548311039.40904  DB epoch: 1548311039.40998
(14362) [Thu Jan 24 06:23:59 2019] MCP Database "ses_siteA1" Local time: Thu Jan 24 06:23:59 2019  DB time: 2019-01-24 06:23:59.40998+00
(14362) [Thu Jan 24 06:23:59 2019] MCP Database "ses_siteA1" Local timezone: UTC (+0000)  DB timezone: UTC
(14362) [Thu Jan 24 06:23:59 2019] MCP Database "ses_siteA1" Postgres version: 90409
(14362) [Thu Jan 24 06:23:59 2019] MCP Database "ses_siteA1" Database port: 8896
(14362) [Thu Jan 24 06:23:59 2019] MCP Database "ses_siteA1" Database host: 10.175.191.125
(14362) [Thu Jan 24 06:23:59 2019] MCP Connecting to database "ses_siteB1" (source)
(14362) [Thu Jan 24 06:23:59 2019] MCP Database "ses_siteB1" Local epoch: 1548311039.42587  DB epoch: 1548311039.42664
(14362) [Thu Jan 24 06:23:59 2019] MCP Database "ses_siteB1" Local time: Thu Jan 24 06:23:59 2019  DB time: 2019-01-24 06:23:59.426636+00
(14362) [Thu Jan 24 06:23:59 2019] MCP Database "ses_siteB1" Local timezone: UTC (+0000)  DB timezone: UTC
.............................
(14362) [Thu Jan 24 06:39:12 2019] MCP Created controller 17774 for sync "sync1". Kick is 0
(17776) [Thu Jan 24 06:39:12 2019] KID (sync1) New kid, sync "sync1" alive=1 Parent=17774 PID=17776 kicked=0 
Use of uninitialized value in concatenation (.) or string at /usr/lib/perl5/site_perl/5.18.2/Bucardo.pm line 3260.
(17776) [Thu Jan 24 06:39:13 2019] KID (sync1) lrs Set database var1 repeatable read var2 repeatable read var3 
(17776) [Thu Jan 24 06:39:13 2019] KID (sync1) lrs Set database "ses_siteA1" to repeatable read read write
(17776) [Thu Jan 24 06:39:13 2019] KID (sync1) lrs Set database "ses_siteB1" to repeatable read read write
(17776) [Thu Jan 24 06:40:16 2019] KID (sync1) Could not serialize, will sleep for 0.5 seconds
Use of uninitialized value in concatenation (.) or string at /usr/lib/perl5/site_perl/5.18.2/Bucardo.pm line 3260.
(17776) [Thu Jan 24 06:40:17 2019] KID (sync1) Set database "ses_siteA1" to repeatable read read write
(17776) [Thu Jan 24 06:40:17 2019] KID (sync1) Set database "ses_siteB1" to repeatable read read write
(17776) [Thu Jan 24 06:40:17 2019] KID (sync1) Conflicts for public.test: 1
(17776) [Thu Jan 24 06:40:17 2019] KID (sync1) Conflicts have been resolved

**Comment by fertiland** [comment]
@machack666 , yes, we tested based bucardo5.5. Would you check the logs above provided by @laorunsen ?

**Comment by fertiland** [comment]
@machack666 ,  This issue was appreared when run bucardo in multi-master mode.  Suppose there are two sites: SiteA, SiteB.  A lot of traffic in the siteA need to be synced to SiteB, meanwhile, app tries to update one of the data to be synced in the delta, then the sync failed in SiteB. As traffic is still soaking, the delta is also increasing very fast.  Then the sync is blocked.  

Now, we tried to change the constraint, the "concurrent update" issue can be fixed. Is there any side effect from your point of view? 
```
ALTER TABLE bucardo.bucardo_config ADD CONSTRAINT valid_config_isolation_level
  CHECK (name <> 'isolation_level' OR (setting IN ('serializable','repeatable read', 'read committed')));
```
In multi-master mode, it seems the probability of changing same record by sync and app is not lower, does this mean that is necessary to promoting the transaction isolation level to "read committed"? 

In active-standby mode, that is ok to use "repeatable read" transaction level.

**Comment by bucardo111** [comment]
> @machack666 , This issue was appreared when run bucardo in multi-master mode. Suppose there are two sites: SiteA, SiteB. A lot of traffic in the siteA need to be synced to SiteB, meanwhile, app tries to update one of the data to be synced in the delta, then the sync failed in SiteB. As traffic is still soaking, the delta is also increasing very fast. Then the sync is blocked.
> 
> Now, we tried to change the constraint, the "concurrent update" issue can be fixed. Is there any side effect from your point of view?
> 
> ```
> ALTER TABLE bucardo.bucardo_config ADD CONSTRAINT valid_config_isolation_level
>   CHECK (name <> 'isolation_level' OR (setting IN ('serializable','repeatable read', 'read committed')));
> ```
> 
> In multi-master mode, it seems the probability of changing same record by sync and app is not lower, does this mean that is necessary to promote the transaction isolation level to "read committed"?
> 
> In active-standby mode, that is ok to use "repeatable read" transaction level.

Hi, has this problem occurred since you changed the isolation level of bucardo to repeatable read?
